---
title: "Case Study 2: Visualizing Global Health Data"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- show mastery of data wrangling techniques, including combining data across different sources and formats, data harmonization, and creation of new variables 
- create effective visual displays of complex information using R and Tableau
- create interactive visual presentations using Tableau

# Case Study Goals
Using data from the World Bank, CIA Factbook, or a complex data source of your own choosing, 
- create a Shiny app in R to illustrate an aspect of our world in data
- create an accompanying Tableau dashboard interactive visual presentation of our world in data

# Data 

R Tutorial Data Set
- [popDF.RData](data/popDF.RData)
- [infMortDF.RData](data/infMortDF.RData)
- [codeMapDF.RData](data/codeMapDF.RData)
- [countries.csv](data/countries.csv)

Full People And Society Data Set:
- [full.RData](data/full.RData)

How To Obtain Data from Factbook:
- [Factbook Tutorial](data/data_file_2014.html)


# Reports

- Final report: the final report will consist of a Shiny app and Tableau dashboard and will be presented to the class as part of a short (5 minute) oral presentation. Data sources must be clearly referenced, and a rationale for the data chosen to tell a story must be provided (one page maximum of written material)

# Resources

Chapter 11 of Data Science in R: A Case Studies Approach to Computational Reasoning and Problem Solving by Nolan and Temple Lang (free e-book through Duke Libraries)

[Introduction to Tableau Video](http://library.capture.duke.edu/Panopto/Pages/Viewer.aspx?id=05708679-00e5-45c3-bb31-fd3724cd8009)


# Slides


[Initial description of CIA Factbook Data and Plotting in R](decks/cs02_1_deck.html)

[Obtaining Tableau Guide](decks/cs02_2_deck.html)

[Tableau visualization of Infant Mortality](decks/cs02_3_deck.html)

[Tableau dashboard visualization of Infant Mortality](decks/cs02_4_deck.html)



