---
title: "Case Study 3: Hierarchical Modeling of Infant Mortality in NC"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- show understanding of use of multilevel models for shrinkage estimation
- understand challenges in fitting and interpreting multilevel models for categorical data
- explain differences in estimation of rates based on small sample sizes when using complete pooling, no pooling, or shrinkage approaches

# Case Study Goals
Based on data from the North Carolina Center for Health Statistics (NCHS), obtain good estimates of infant mortality rates in NC from 2011-2016 based on county, year, and race/ethnicity. Determine whether any groups (defined by county, race/ethnicity, or their combination) are experiencing changes in infant mortality rates and describe those changes. Assess whether some groups or areas have significantly higher infant mortality rates than others. Assess whether patterns in infant mortality by race/ethnicity in NC mirror national trends. All assessments should involve characterization of uncertainty.

# Data

-Data from NC Birth and Death Records will be made available on Sakai 
 

# Reports

- Interim report 1: create an engaging visualization of observed infant mortality rates by year, county and race
- Interim report 2: using a hierarchical model, obtain estimates of infant mortality rates in 2015 by county and race/ethnicity and create your own version of the 2015 table published by SCHS. Compare your estimates to the published estimates from the SCHS and discuss any discrepancies in detail. Your report should include your table and visualization of estimates (and observed values) for 2015, a one page (maximum) description of the model used, 1-2 pages describing your findings, and a 1-2 page report targeted at SCHS explaining how use of your model to obtain estimated rates compares to the methods you have seen them use so far, which are pooling years (as in the 2010-2014 graphic) or reporting rates based on small cell counts (as in 2015). In your report targeted to SCHS, if you feel they should use different methodology (e.g., your model) for estimating infant mortality rates, be sure to make a clear argument for doing so. The maximum length of this report is 7 pages. All results should be fully reproducible. 
- Final report: prepare a report, not to exceed 10 pages and accompanied by useful visualizations, describing infant mortality in NC by county and race/ethnicity, along with any trends over time overall or in subgroups.  All results should be fully reproducible. 


# Resources

Data Analysis Using Regression and Multilevel/Hierarchical Models by Gelman & Hill (Chapters 12-15 in particular)

[2015 NC Infant Mortality Rates, from NC State Center for Health Statistics](NCinfantmortalityrates.pdf)


# Slides



- [Infant Mortality in NC](decks/cs03_1_deck.html)

- [Binomial regression ](decks/cs03_2_deck.html)


- [Multilevel models for Gaussian data](decks/cs03_3_deck.html)

- [Multilevel models for binary data](decks/cs03_4_deck.html)

- [MLM case study: Red State, Blue State](decks/cs03_5_deck.html)



