---
title: "Case Study 4: Election Prediction"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```




# Learning Objectives

- continue developing skills in using models for prediction
- evaluate and update predictions based on dynamic data
- combine data on a variety of levels (national, state, individual) to predict election outcomes

# Case Study Goals
Goals of this case study are (1) to predict whether the US House of Representatives remains in Republican control, and (2) to predict the outcomes of all NC Congressional elections (the 13 federal Representatives to Congress), including characterization of uncertainty in predictions.

We will present predictions weekly, and the final case study grading criteria will include some determined by the class. In addition, prizes will be given in a number of categories (e.g., most creative useful data source).

# Data



- [gay_marriage_megapoll.dta](decks/data/gay_marriage_megapoll.dta)
- [NC voter files](https://dl.ncsbe.gov/?prefix=data/)
- [Other NC voter data](https://www.ncsbe.gov/data-stats/other-election-related-data)
- [Cooperative Congressional Election Study](https://cces.gov.harvard.edu/pages/welcome-cooperative-congressional-election-study) - [Opportunity Insights Data Library](https://opportunityinsights.org/data/?geographic_level=0&topic=0&paper_id=0#resource-listing)
- See data on Sakai under Resources in the CS4 folder for 2010 Census summary data and 2016 voting data in NC


# Reports

- Weekly predictions of the NC Congressional races and whether the House of Representatives will flip to Democratic control starting October 12
- Interim report 1: who votes in NC? Using the NC voter files, identify who votes in NC so that these data can be used with election surveys in order to predict outcomes of NC congressional elections. Present results in short in-class presentation and in accompanying report not to exceed 5 pages.  Results should be fully reproducible. 
- Interim report 2: in 5 pages (maximum), outline your models and general strategy for predicting the outcome of the 2018 elections.
- Final report: provide point and interval estimates of the % of votes won by each NC Congressional candidate, predicting the winner of each race. Provide point and interval estimates of the probability that the US House of Representatives remains under Republican control after the 2018 election.


# Resources

+ [Andy Gelman Interview on Election Forecasting](https://www.datacamp.com/community/blog/election-forecasting-polling)
(This is a very interesting interview overall. I suggest listening to it all, but the polling/election modeling component starts about 30 minutes into the interview.)
+ [Who is running for office, and which districts are viewed as competitive?](https://www.270towin.com/2018-house-election/)
+ [Nate Silver says this is going to be easy!](https://www.newsobserver.com/news/politics-government/article216882230.html)
+ [ASA 2016 Election Contest](http://thisisstatistics.org/demystifying-the-election-prediction-2016-contest/)
+ [Why do we care about likely voters?]( https://fivethirtyeight.com/features/registered-voter-polls-will-usually-overrate-democrats/)
+ [FiveThirtyEight's 2016 forecast details]( https://fivethirtyeight.com/features/a-users-guide-to-fivethirtyeights-2016-general-election-forecast/) 
+ [FiveThirtyEight's current forecasts](https://projects.fivethirtyeight.com/2018-midterm-election-forecast/house/?ex_cid=rrpromo)
+ [Potentially helpful blog 1]( https://www.r-statistics.com/2016/08/presidential-election-predictions-2016/)
+ [Potentially helpful blog 2]( https://github.com/hardin47/prediction2016/blob/master/predblog.pdf)
+ [Worst 2016 Political Predictions](https://www.politico.com/magazine/story/2016/12/the-worst-political-predictions-of-2016-214555)
+ [Polling trends](https://www-m.cnn.com/2018/10/02/politics/trump-brett-kavanaugh-turning-point-election-educated-white-women-voters/index.html?r=https%3A%2F%2Fwww.cnn.com%2F)
+ [Cool article on sensitivity of polls](https://www.nytimes.com/2016/10/13/upshot/how-one-19-year-old-illinois-man-is-distorting-national-polling-averages.html)
+ [Google Street View and Voting](https://www.citylab.com/transportation/2017/12/google-street-view-data-demographics-cars-research/547436/)
+ [Pickup Trucks and Voting](http://www.thedrive.com/news/16712/trump-supporting-towns-more-likely-to-be-filled-with-pickup-trucks-study-claims)

# Slides 


- [Basics of Election Prediction](decks/cs04_1_deck.html)
- [Poststratification and Weighting](decks/cs04_2_deck.html)
- [MRP Tutorial](decks/cs04_3_deck.html)



# Prizes

Prizes may be awarded in the following categories:

(1) best prediction (who wins each NC house seat + House control + tiebreak of exact number of seats won by Democrats, Republicans, and others in US House of Representatives + second tiebreak of \% of vote share by winning candidate in NC 9th district)
(2) most creative data source useful for prediction (e.g., Yeti sales, number of nail salons per capita, tweets)
(3) most easily accessibile new data source useful for prediction
(4) best interactive visualization





