---
title: "Case Study 5: Surviving Missing Data"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- understand different types of missing data mechanisms and potential implications on validity of analysis results
- understand and apply statistical methods for survival analysis; understand role of missing data induced by censoring of events
- apply modern methods for handling missing data to analyze time-to-event data for Duke cardiology patients

# Case Study Goals

Based on data from the Duke Databank for Cardiovascular Diseases, we will explore biological and sociodemographic factors related to survival. The goal is to describe both modifiable and non-modifiable risk factors for death, accounting as much as possible for potential biases due to missing data.

# Data 

The Duke data are available on Sakai. Please do not distribute these data beyond the class.

# Reports

- Interim report: Produce a 5 page (maximum) report in R markdown that explores the missing data patterns and mechanisms to the extent possible based on the data provided. Comment on the potential for missing data to bias analysis results.

- Final report: Produce a 5 page (maximum) report in R markdown that explores factors related to survival in this cohort. Your analysis should account for missing data in a principled manner designed to limit potential bias in results.



# Resources 

-For more on missing data, check out [Michael Akande's talk (dated 11/5)](https://trinity.capture.duke.edu/Panopto/Pages/Sessions/List.aspx?folderID=2952f554-d9c8-4749-b8c4-a949013da84e)




# Slides 

[Duke Databank for Cardiovascular Disease](decks/cs05_1_deck.html)


[Missing Data Tutorial](decks/cs05_2_deck.html)


[Survival analysis tutorial](decks/cs05_3_deck.html)

[Survival with missing data](decks/cs05_4_deck.html)



