---
title: "Case Study 7: Navigating Perils of Small Samples"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- understand when is a sample small
- understand potential pitfalls and pressure points when dealing with small samples
- learn some methods to analyze
- learn some methods to avoid needing small sample methods/maximize data you have
- talk about design methods to start to avoid small samples (e.g., stratified sampling)

# Case Study Goals
Based on data from the Duke Databank for Cardiovascular Diseases, we will explore biological and sociodemographic factors related to survival. In order to 

# Data

-Jiurui post data on Sakai with data dictionary linked here; variables to include in dataset include the following:  AGE_G, GENDER, RACE_G, YRCATH_G, CHFSEV, HXCEREB, HXCHF, HXCOPD, HXDIAB, HXHTN, HXMI, HXHYL, HXSMOKE, HEIGHT_R, WEIGHT_R, (calculate BMI from height and weight),  S3, LMST, LVEF_R, NUMDZV, DEATH, DAYS2LKA
-Jiurui let me know % with missing data for each variable. Also subset to one observation per person (repeat events are included, but there should be only one death)
-NOtes: look at race by gender interaction, 
- outcome should be time to death. Have Jiurui construct this bearing in mind the censoring variable

# Reports



# Resources




# Slides



