---
title: "Individual Case Study"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- learn to scrape data from HTML pages
- manipulate data obtained from HTML pages in R 
- create helpful R functions to analyze web data and extract useful information
- create interactive function/app for analysis of identified data

# Case Study Goals

In the individual case study, you will design a Shiny app or other presentation/visualization of interesting data (e.g., data related to your career interests), presenting your work in class in December. Your presentation will lead the class through the resources you have designed.




# Data

- Data should be obtained via web scraping or use of a dynamic online resource. Software should be able to relatively easily accommodate regular updates to the data, to the extent possible.

# Reports

- Interim report 1: analysis plan for design of individual case study
- Interim report 2: 3 page maximum draft of final report
- Final report: 3 page maximum written report and oral presentation in class, guides students through your newly designed resource (which should be uploaded under Assignments)

Grades are based on the final report; the purpose of the interim reports is to provide you with guidance and feedback along the way.


# Resources

Nolan and Temple Lang, Chapter 12 (some of this chapter is now outdated)


# Slides 


[Web Scraping](decks/cs06_1_deck.html)
<!---
[Web Scraping and Analysis: Jiurui based on 12.4-12.9](decks/cs_indiv_3_deck.html)

--->


